#!/usr/bin/env python3
"""
Generate QCM questions for ELLLO audio comprehension exercises using Gemini API (free tier).

Usage:
    GEMINI_API_KEY=AIza... python3 scripts/generate_comprehension_qcm.py

Options:
    --catalog   Path to catalog.json   (default: DownloadMP3/ello_b2/catalog.json)
    --audio-dir Path to ello_b2 folder (default: DownloadMP3/ello_b2)
    --out       Output JS file         (default: data/comprehension-audio.js)
    --limit     Max entries to process (default: all)
    --dry-run   Print prompts, no API calls
"""

import argparse
import json
import os
import re
import sys
import time

try:
    from google import genai
except ImportError:
    print("Missing dependency: pip install google-genai")
    sys.exit(1)

CHECKPOINT_FILE = "scripts/.qcm_checkpoint.json"

PROMPT_TEMPLATE = """You are an English language teacher creating TOEIC-style comprehension questions.

For the transcript below, generate exactly 3 multiple-choice questions.

Rules:
- Question 1: main idea or purpose of the audio
- Question 2: specific detail directly stated in the transcript
- Question 3: inference or speaker's attitude/intention
- 4 options each (A, B, C, D), only one correct
- Distractors must be plausible, not obviously wrong
- Explanation in French (1-2 sentences max), citing the key phrase
- Difficulty: B2 level
- Return ONLY a valid JSON array, no extra text, no markdown

Transcript:
---
{transcript}
---

Return ONLY this JSON array:
[
  {{
    "id": "q1",
    "prompt": "...",
    "options": ["A. ...", "B. ...", "C. ...", "D. ..."],
    "correct": "A",
    "explanation": "..."
  }},
  {{
    "id": "q2",
    "prompt": "...",
    "options": ["A. ...", "B. ...", "C. ...", "D. ..."],
    "correct": "B",
    "explanation": "..."
  }},
  {{
    "id": "q3",
    "prompt": "...",
    "options": ["A. ...", "B. ...", "C. ...", "D. ..."],
    "correct": "C",
    "explanation": "..."
  }}
]"""


def load_checkpoint():
    if os.path.exists(CHECKPOINT_FILE):
        with open(CHECKPOINT_FILE) as f:
            return json.load(f)
    return {}


def save_checkpoint(cp):
    os.makedirs(os.path.dirname(CHECKPOINT_FILE), exist_ok=True)
    with open(CHECKPOINT_FILE, "w") as f:
        json.dump(cp, f, indent=2)


def read_transcript(audio_dir, local_path):
    path = os.path.join(audio_dir, local_path)
    if not os.path.exists(path):
        return None
    with open(path, encoding="utf-8", errors="ignore") as f:
        return f.read().strip()


def call_gemini(client, transcript, dry_run=False):
    if dry_run:
        print("  [DRY RUN] Would call Gemini with", len(transcript), "chars")
        return [
            {"id": "q1", "prompt": "PLACEHOLDER Q1", "options": ["A. x", "B. y", "C. z", "D. w"], "correct": "A", "explanation": "placeholder"},
            {"id": "q2", "prompt": "PLACEHOLDER Q2", "options": ["A. x", "B. y", "C. z", "D. w"], "correct": "B", "explanation": "placeholder"},
            {"id": "q3", "prompt": "PLACEHOLDER Q3", "options": ["A. x", "B. y", "C. z", "D. w"], "correct": "C", "explanation": "placeholder"},
        ]

    prompt = PROMPT_TEMPLATE.format(transcript=transcript[:3000])
    response = client.models.generate_content(model="gemini-2.0-flash-lite", contents=prompt)
    raw = response.text.strip()

    # Extract JSON array even if Gemini adds surrounding text or markdown
    raw = re.sub(r'^```json\s*', '', raw)
    raw = re.sub(r'^```\s*', '', raw)
    raw = re.sub(r'\s*```$', '', raw)
    match = re.search(r'\[.*\]', raw, re.DOTALL)
    if not match:
        raise ValueError(f"No JSON array found in response: {raw[:200]}")
    return json.loads(match.group())


def build_js(entries):
    lines = [
        "/* AUTO-GENERATED by scripts/generate_comprehension_qcm.py (Gemini API) */",
        "/* Re-run the script to update. Do not edit manually. */",
        "",
        "const COMPREHENSION_AUDIO = [",
    ]
    for e in entries:
        lines.append("  " + json.dumps(e, ensure_ascii=False) + ",")
    lines.append("];")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--catalog", default="DownloadMP3/ello_b2/catalog.json")
    parser.add_argument("--audio-dir", default="DownloadMP3/ello_b2")
    parser.add_argument("--out", default="data/comprehension-audio.js")
    parser.add_argument("--limit", type=int, default=None)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    # Run from project root
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    os.chdir(project_root)

    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key and not args.dry_run:
        print("Error: GEMINI_API_KEY not set.")
        print("Get a free key at: https://aistudio.google.com/app/apikey")
        print("Then run: GEMINI_API_KEY=AIza... python3 scripts/generate_comprehension_qcm.py")
        sys.exit(1)

    client = None
    if not args.dry_run:
        client = genai.Client(api_key=api_key)

    with open(args.catalog, encoding="utf-8") as f:
        catalog = json.load(f)

    if args.limit:
        catalog = catalog[:args.limit]

    checkpoint = load_checkpoint()
    results = []
    skipped = 0
    processed = 0
    errors = 0

    print(f"Processing {len(catalog)} entries with Gemini...")

    for i, entry in enumerate(catalog):
        eid = entry["id"]

        if eid in checkpoint:
            results.append(checkpoint[eid])
            skipped += 1
            continue

        transcript = read_transcript(args.audio_dir, entry["local_transcript"])
        if not transcript:
            print(f"  [{i+1}/{len(catalog)}] SKIP (no transcript): {eid}")
            errors += 1
            continue

        print(f"  [{i+1}/{len(catalog)}] {eid} — {entry['title'][:50]}")

        try:
            questions = call_gemini(client, transcript, dry_run=args.dry_run)
            record = {
                "id": eid,
                "section": entry["section"],
                "title": entry["title"],
                "audioPath": entry["local_mp3"],
                "transcript": transcript,
                "questions": questions,
            }
            results.append(record)
            checkpoint[eid] = record
            save_checkpoint(checkpoint)
            processed += 1
        except Exception as exc:
            print(f"    ERROR: {exc}")
            errors += 1

        # Gemini free tier: 15 requests/min → 1 request every 4s to stay safe
        if not args.dry_run:
            time.sleep(4)

    js = build_js(results)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(js)

    print(f"\nDone. {processed} generated, {skipped} from cache, {errors} errors.")
    print(f"Output: {args.out} ({len(results)} exercises total)")


if __name__ == "__main__":
    main()
