#!/usr/bin/env python3
"""
Generate QCM questions for ELLLO audio comprehension exercises.

Usage:
    ANTHROPIC_API_KEY=sk-ant-... python3 scripts/generate_comprehension_qcm.py

Options:
    --catalog   Path to catalog.json   (default: DownloadMP3/ello_b2/catalog.json)
    --audio-dir Path to ello_b2 folder (default: DownloadMP3/ello_b2)
    --out       Output JS file         (default: data/comprehension-audio.js)
    --limit     Max entries to process (default: all)
    --dry-run   Print prompts, no API calls
"""

import argparse
import json
import os
import re
import sys
import time

try:
    import anthropic
except ImportError:
    print("Missing dependency: pip install anthropic")
    sys.exit(1)

CHECKPOINT_FILE = "scripts/.qcm_checkpoint.json"

SYSTEM_PROMPT = """You are an English language teacher creating TOEIC-style comprehension questions.
For a given audio transcript, you generate exactly 3 multiple-choice questions in JSON format.
Rules:
- Question 1: main idea / purpose of the audio
- Question 2: specific detail directly stated in the transcript
- Question 3: inference or speaker's attitude/intention
- 4 options each (A, B, C, D), only one correct
- Distractors must be plausible, not obviously wrong
- Explanation in French (1-2 sentences), citing the key phrase from the transcript
- Difficulty level: B2
- Return ONLY a JSON array, no commentary."""

USER_TEMPLATE = """Transcript:
---
{transcript}
---

Generate 3 TOEIC Part 3/4 style QCM questions. Return ONLY this JSON array:
[
  {{
    "id": "q1",
    "prompt": "...",
    "options": ["A. ...", "B. ...", "C. ...", "D. ..."],
    "correct": "A",
    "explanation": "..."
  }},
  {{
    "id": "q2",
    "prompt": "...",
    "options": ["A. ...", "B. ...", "C. ...", "D. ..."],
    "correct": "B",
    "explanation": "..."
  }},
  {{
    "id": "q3",
    "prompt": "...",
    "options": ["A. ...", "B. ...", "C. ...", "D. ..."],
    "correct": "C",
    "explanation": "..."
  }}
]"""


def load_checkpoint():
    if os.path.exists(CHECKPOINT_FILE):
        with open(CHECKPOINT_FILE) as f:
            return json.load(f)
    return {}


def save_checkpoint(cp):
    os.makedirs(os.path.dirname(CHECKPOINT_FILE), exist_ok=True)
    with open(CHECKPOINT_FILE, "w") as f:
        json.dump(cp, f, indent=2)


def read_transcript(audio_dir, local_path):
    path = os.path.join(audio_dir, local_path)
    if not os.path.exists(path):
        return None
    with open(path, encoding="utf-8", errors="ignore") as f:
        return f.read().strip()


def call_claude(client, transcript, dry_run=False):
    if dry_run:
        print("  [DRY RUN] Would call Claude with", len(transcript), "chars")
        return [
            {"id": "q1", "prompt": "PLACEHOLDER", "options": ["A. x", "B. y", "C. z", "D. w"], "correct": "A", "explanation": "placeholder"},
            {"id": "q2", "prompt": "PLACEHOLDER", "options": ["A. x", "B. y", "C. z", "D. w"], "correct": "B", "explanation": "placeholder"},
            {"id": "q3", "prompt": "PLACEHOLDER", "options": ["A. x", "B. y", "C. z", "D. w"], "correct": "C", "explanation": "placeholder"},
        ]

    resp = client.messages.create(
        model="claude-haiku-4-5-20251001",
        max_tokens=1024,
        system=SYSTEM_PROMPT,
        messages=[{"role": "user", "content": USER_TEMPLATE.format(transcript=transcript[:3000])}],
    )
    raw = resp.content[0].text.strip()
    # Extract JSON array even if Claude adds surrounding text
    match = re.search(r'\[.*\]', raw, re.DOTALL)
    if not match:
        raise ValueError(f"No JSON array found in response: {raw[:200]}")
    return json.loads(match.group())


def slug_to_audiopath(local_mp3):
    return local_mp3  # already "section/slug/audio.mp3"


def build_js(entries):
    lines = [
        "/* AUTO-GENERATED by scripts/generate_comprehension_qcm.py */",
        "/* Re-run the script to update. Do not edit manually. */",
        "",
        "const COMPREHENSION_AUDIO = [",
    ]
    for e in entries:
        lines.append("  " + json.dumps(e, ensure_ascii=False) + ",")
    lines.append("];")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--catalog", default="DownloadMP3/ello_b2/catalog.json")
    parser.add_argument("--audio-dir", default="DownloadMP3/ello_b2")
    parser.add_argument("--out", default="data/comprehension-audio.js")
    parser.add_argument("--limit", type=int, default=None)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    # Change to project root (script may be called from anywhere)
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    os.chdir(project_root)

    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key and not args.dry_run:
        print("Error: ANTHROPIC_API_KEY not set. Use --dry-run to test without API.")
        sys.exit(1)

    client = anthropic.Anthropic(api_key=api_key) if not args.dry_run else None

    with open(args.catalog, encoding="utf-8") as f:
        catalog = json.load(f)

    if args.limit:
        catalog = catalog[:args.limit]

    checkpoint = load_checkpoint()
    results = []
    skipped = 0
    processed = 0
    errors = 0

    print(f"Processing {len(catalog)} entries...")

    for i, entry in enumerate(catalog):
        eid = entry["id"]

        # Already done?
        if eid in checkpoint:
            results.append(checkpoint[eid])
            skipped += 1
            continue

        transcript = read_transcript(args.audio_dir, entry["local_transcript"])
        if not transcript:
            print(f"  [{i+1}/{len(catalog)}] SKIP (no transcript): {eid}")
            errors += 1
            continue

        print(f"  [{i+1}/{len(catalog)}] Generating: {eid} — {entry['title'][:50]}")

        try:
            questions = call_claude(client, transcript, dry_run=args.dry_run)
            record = {
                "id": eid,
                "section": entry["section"],
                "title": entry["title"],
                "audioPath": entry["local_mp3"],
                "transcript": transcript,
                "questions": questions,
            }
            results.append(record)
            checkpoint[eid] = record
            save_checkpoint(checkpoint)
            processed += 1
        except Exception as exc:
            print(f"    ERROR: {exc}")
            errors += 1

        if not args.dry_run:
            time.sleep(0.3)  # polite rate limiting

    # Write JS output
    js = build_js(results)
    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(js)

    print(f"\nDone. {processed} generated, {skipped} from cache, {errors} errors.")
    print(f"Output: {args.out}")


if __name__ == "__main__":
    main()
